### ISSUE TITLE
Improve some comment styling details

### ISSUE THREAD

**Issue by luukdv** [trendwerk/sphynx#708]
It is already improved in #705, but some details still need to be taken care of (like reply form margins and comment date position on smaller screens).

**Comment by sboerrigter** [comment]
Maybe we could drop reply support to make the comment forms cleaner?

**Comment by luukdv** [comment]
Is there a way to support general replies but not inline? That's what you mean right? I think that's a good idea.

**Comment by sboerrigter** [comment]
Yes, that's what I mean. This would get rid of all the "reply" links and the button behind the title in the comment form. I think this would make it a lot cleaner.

**Comment by luukdv** [comment]
@haroldangenent what do you think?

**Comment by haroldangenent** [comment]
I don't agree. I think at least admins or bloggers should be able to respond to a comment. Otherwise discussion about an article is not possible at all and comments seem futile.

By default, this is not necessary in TrendPress, that's why we will remove comments in #704.

@luukdv I see you've removed the milestone, but actually this got in the latest release.

**Comment by haroldangenent** [comment]
Closing this, there are no comments in Sphynx anymore.
