### ISSUE TITLE
`npm` first with Yarn

### ISSUE THREAD

**Issue by haroldangenent** [trendwerk/sphynx#736]
Use `npm` first (drop Bower for packages that are available on `npm`).

**Comment by luukdv** [comment]
Agreed.

**Comment by luukdv** [comment]
Maybe we should try Yarn, to keep things consistent. It can grab packages from npm, Bower, GitHub, Bitbucket and the likes.

- https://code.facebook.com/posts/1840075619545360/yarn-a-new-package-manager-for-javascript/
- https://yarnpkg.com/

**Comment by luukdv** [comment]
Tested Yarn, works like a charm and is very fast. Currently it can't grab packages like https://github.com/trendwerk/toggle-navigation/ because there's no information like `name` in the `package.json`: https://github.com/trendwerk/toggle-navigation/blob/master/package.json. Maybe we should drop the `bower` file and focus on NPM for other packages too.
