### ISSUE TITLE
Move post.twig and post-meta.twig to partials/posts

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/sphynx#799]
* `partials/post.twig` > `partials/post/post.twig`
* `partials/post-meta.twig` > `partials/post/meta.twig`

Ok?

**Comment by luukdv** [comment]
Although it's trivial (probably not worth the time), I don't think `/post/post` is logical - `post` is not a component inside a `post`.

`partials/post.twig` and `partials/post/meta.twig` are more semantic. Since there would be only one component a separate folder is not really necessary, so I understand the choice of leaving this out.

**Comment by sboerrigter** [comment]
I am okay with your suggestion to keep `partials/post.twig` since it is no part of the post component.

But I think structuring components into folders is a good idea. It might seem overcomplicated for just one component, but since this is a starter theme, there will probably be added more during development. That is why I think we should setup a good folder structure. Otherwise we would have to move this file for every project we start.

**Comment by sboerrigter** [comment]
On second thought. `post-meta.twig` could also be a shared component. I do suggest to rename it to `meta.twig` to match the CSS class.
